import ButtonLInk, { Button } from "@/components/button";
import Container from "@/components/container";
import Header from "@/components/header";
import { Title } from "@/components/title";
import Head from "next/head";
import Image from "next/image";
import { faFacebook, faInstagram, faPix} from "@fortawesome/free-brands-svg-icons";
import { faCheckCircle, faCreditCard} from "@fortawesome/free-regular-svg-icons";
import {  faBarcode, faCircleDollarToSlot, faCoins, faIdCard, faRotate, faSackDollar, faShoppingCart } from "@fortawesome/free-solid-svg-icons";
import Link from "next/link";
import { CardIcon } from "@/components/icon";
import logoWiinpay from '@/assets/wiinpay.png'

export default function Home() {

  return (
    <>
      <Head>
        <title>Wiinpay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Link rel="icon" href={logoWiinpay}></Link>
      </Head>
      <main>

        <div className="w-full flex flex-col justify-center items-center bg-black">

          <Header/>

          <section className="flex mx-auto h-full w-full bg-black justify-center items-center my-[150px]"> 
            <div className="w-full max-w-[1100px] flex gap-3 justify-between items-center m-3 max-[770px]:flex-col-reverse">
                <Container>
                  <Title className="font-bold text-5xl text-white max-[385px]:text-3xl">Receba no <span className="text-purple-600">PIX</span> e no <span className="text-purple-600">cartão</span>. Sem <span className="text-purple-600!">enrolação</span>. Sem <span className="text-purple-600">bloqueios</span>.</Title>
                  <Button className={'bg-purple-600 text-black w-[200px] h-[60px] font-medium text-xl'}>Comece a vender!</Button>
                  <p className="font-medium text-3xl text-white max-[385px]:text-2xl">Aumente suas <span className="text-purple-600">vendas</span> com uma <span className="text-purple-600">Api de pagamentos</span> feita para quem precisa de <span className="text-purple-600">velocidade</span>, <span className="text-purple-600">liberdade</span> e <span className="text-purple-600">dinheiro</span> no bolso.</p>
                </Container>
                <Image src={logoWiinpay} className="max-w-[350px] w-full h-auto"/>
            </div>
          </section>

          <section className="flex flex-col mx-auto h-full w-full bg-[#0F0F0F] justify-center items-center pt-8 pb-[200px] relative"> 
            <div className="w-full h-full max-w-[1100px] flex flex-col gap-5 justify-center items-center text-center mx-3">
                <p className="max-w-[700px] font-medium text-2xl text-white">Redefina a maneira como você acessa os ganhos de suas vendas com nossa <span className="text-purple-600">solução de pagamentos online</span>.</p>
                <div className="m-3 grid grid-cols-3 items-center justify-between gap-5 max-[590px]:grid-cols-2 max-[410px]:grid-cols-1">
                    <Container className={'max-w-[320px]'}>
                        <CardIcon icon={faCreditCard} />
                        <Title className="font-bold text-2xl text-purple-600">Cartão de crédito (D+2)</Title>
                        <p className="font-bold text-white">Receba em D+2 vendas de cartão, e mantenha sua operação girando.</p>                       
                    </Container>
                    <Container className={'max-w-[320px]'}>
                        <CardIcon icon={faPix} />
                        <Title className="font-bold text-2xl text-purple-600">Pix (D+0)</Title>
                        <p className="font-bold text-white">Receba na hora o dinheiro dos pagamentos feitos por PIX.</p>                       
                    </Container>
                    <Container className={'max-w-[320px]'}>
                        <CardIcon icon={faBarcode} />
                        <Title className="font-bold text-2xl text-purple-600">Boleto (D+0)</Title>
                        <p className="font-bold text-white">Receba o dinheiro na mesma hora que o boleto for compensado.</p>                       
                    </Container>
                </div>
                <Button className={'bg-purple-600 text-black w-[200px] h-[60px] font-medium text-xl'}>Comece a vender!</Button>
            </div>

            <section class="bg-white max-w-[1100px] absolute bottom-[100px] flex flex-row justify-center items-center gap-10 overflow-hidden rounded-[16px] shadow-[0px_0px_48px_-16px_rgba(0,0,0,0.26)] mt-10 mb-[-238px] py-11 px-11 z-100 transition-all duration-300 max-[970px]:flex-col max-[970px]:relative">
              <Image className='w-full max-w-[200px] h-full' src={logoWiinpay}/>
              <div>
                  <Title className="font-bold text-[#102539] text-3xl">Sobre a <span className="text-purple-600">Wiinpay</span></Title>
                  <p className="font-medium text-[#102539]">Nosso objetivo é oferecer soluções de pagamento dinâmicas e personalizadas, focadas exatamente no que o nosso cliente precisa e no momento em que precisa.</p>
                  <p className="font-medium text-[#102539]">Somos uma plataforma PRÓPRIA trazendo mais SEGURANÇA para você seller escalar sua operação sem saques travados ou correr o risco de uma plataforma qualquer sumir com seu dinheiro.</p>
              </div>
            </section>
          </section>

          <section className="flex mx-auto h-full w-full bg-black justify-center items-center my-[150px]"> 
            <div className="w-full max-w-[1100px] flex gap-3 justify-center flex-col items-center m-3">
                <Title>Conheça nossos beneficios</Title>
                <div className="w-full m-3 grid grid-cols-3 items-center justify-center gap-5 max-[1000px]:grid-cols-2 max-[600px]:grid-cols-1">
                    <Container className={'w-full p-5 bg-[#0f0f0f] border border-[#54595f] rounded-xl'}>
                        <CardIcon icon={faShoppingCart} />
                        <Title>Checkout Personalizado</Title>
                        <p className="font-bold text-white">Customize seu checkout para que ele reflita a identidade da sua marca.</p>                       
                        <p className="font-bold text-white">Transmita confiança aos seus clientes e impulsione as taxas de conversão.</p>                       
                    </Container>

                    <Container className={'w-full p-5 bg-[#0f0f0f] border border-[#54595f] rounded-xl'}>
                        <CardIcon icon={faCircleDollarToSlot} />
                        <Title>Taxa de Aprovação de 97%</Title>
                        <p className="font-bold text-white">Com o nosso avançado sistema de multiadquirência, a Wiinpay atinge uma impressionante taxa de aprovação de 97%.</p>                       
                        <p className="font-bold text-white">Isso significa mais transações bem-sucedidas e menos frustrações para o seu negócio.</p>                       
                    </Container>

                    <Container className={'w-full p-5 bg-[#0f0f0f] border border-[#54595f] rounded-xl'}>
                        <CardIcon icon={faIdCard} />
                        <Title>Recebimento Cartão em D+2:</Title>
                        <p className="font-bold text-white">Na Wiinpay, entendemos a importância de um fluxo de caixa eficiente.</p>                       
                        <p className="font-bold text-white">Com nossos pagamentos em D+2 para vendas no cartão, ajudamos a manter sua operação girando suavemente.</p>                       
                    </Container>

                    <Container className={'w-full p-5 bg-[#0f0f0f] border border-[#54595f] rounded-xl'}>
                        <CardIcon icon={faRotate} />
                        <Title>Sistema de Pré-chargeback</Title>
                        <p className="font-bold text-white">Nossa abordagem proativa ao gerenciamento de pré-chargebacks minimiza significativamente as disputas.</p>                       
                        <p className="font-bold text-white">Com a Wiinpay, você tem a vantagem de resolver questões de reembolso antes que se transformem em chargebacks, mantendo baixas taxas e otimizando o atendimento ao cliente.</p>                       
                    </Container>

                    <Container className={'w-full p-5 bg-[#0f0f0f] border border-[#54595f] rounded-xl'}>
                        <CardIcon icon={faPix} />
                        <Title>Recebimento PIX em D+0</Title>
                        <p className="font-bold text-white">Agilidade é fundamental, e com a Wiinpay, os pagamentos via PIX são recebidos instantaneamente.</p>                       
                        <p className="font-bold text-white">Aproveite a eficiência de ter seu dinheiro disponível no mesmo dia e escale suas campanhas.</p>                       
                    </Container>

                    <Container className={'w-full p-5 bg-[#0f0f0f] border border-[#54595f] rounded-xl'}>
                        <CardIcon icon={faCoins} />
                        <Title>Saque Instantâneo</Title>
                        <p className="font-bold text-white">Na Wiinpay, seu dinheiro está disponível imediatamente após solicitar um saque.</p>                       
                        <p className="font-bold text-white">A rapidez na liquidez é mais um de nossos compromissos com o sucesso do seu negócio.</p>                       
                    </Container>

                    <Container className={'w-full p-5 bg-[#0f0f0f] border border-[#54595f] rounded-xl'}>
                        <CardIcon icon={faSackDollar} />
                        <Title>Upsell e Order Bumps</Title>
                        <p className="font-bold text-white">Com os recursos de upsell e order bumps da Wiinpay, nossos clientes veem um aumento de até 25% no faturamento.</p>                       
                        <p className="font-bold text-white">Estes são instrumentos poderosos para maximizar cada venda.</p>
                    </Container>

                    <Container className={'flex-row justify-center items-center col-span-2 p-5 w-full py-5 bg-[#202020] rounded-xl max-[1000px]:col-span-1 max-[1000px]:flex-col'}>
                        <span className="flex flex-col gap-3 text-xl max-[700px]:items-center">
                            <p className="font-bold text-white">Com a Wiinpay, cada aspecto do seu processo de pagamento é pensado para impulsionar o crescimento e a eficiência do seu negócio.</p>
                            <Button className={'bg-purple-600 text-black w-[200px] h-[60px] font-medium text-xl'}>Comece a vender!</Button>
                        </span>
                        <img src='https://versellpay.com/wp-content/uploads/2024/10/Group-7561-1024x619.webp' className="h-auto max-w-[400px] w-full"/>
                    </Container>
                </div>
                
            </div>
          </section>

          <section className="flex mx-auto h-full w-full bg-black justify-center items-center"> 
              <div className="flex flex-row max-w-[1100px] justify-center items-center flex-grow self-stretch transition-colors duration-300 border border-solid border-purple-600 rounded-[24px] p-5 gap-5 z-0 m-3 max-[750px]:flex-col">
                  <Title>Fatura mais de R$50 mil por mês?</Title>
                  <p className="font-bold text-white text-xl max-w-[300px]">Fale com um Gerente VIP. Temos taxas e benefícios exclusivas para seu negócio.</p>
                  <Button className={'bg-purple-600 w-[200px] h-[60px] text-black font-medium text-xl'}>Falar com gerente</Button>
              </div>
          </section>

          <section className="flex mx-auto h-full w-full bg-black justify-center items-center">
              <div className="w-full max-w-[1100px] flex justify-end items-center">
                  <Button className={'text-white w-[200px]'}>Voltar para o topo</Button>
              </div>
          </section>

          <section className="flex mx-auto h-full w-full bg-black justify-center items-center">
              <div className="w-full max-w-[1100px] flex gap-5 justify-between items-center m-3 border-y border-[#54595f] p-8 max-[550px]:flex-col max-[550px]:justify-center">
                  <Container className={'max-[550px]:items-center'}>
                    <Image className='max-w-[100px] w-full h-auto' src={logoWiinpay}/>
                    <span className="flex gap-5">
                        <ButtonLInk icon={faFacebook} link={'https://www.facebook.com/Wiinpaybank'}/>
                        <ButtonLInk icon={faInstagram} link={'https://www.instagram.com/Wiinpay/'}/>
                    </span>
                  </Container>

                  <Container className={'max-[550px]:items-center'}>
                      <p className="text-white font-bold">Políticas e Termos</p>
                      <a className="text-[#54595f] font-medium underline">Política de privacidade</a>
                      <a className="text-[#54595f] font-medium underline">Termos de uso</a>
                      <a className="text-[#54595f] font-medium underline">Política de Prevenção a lavagem de dinheiro</a>
                      <a className="text-[#54595f] font-medium underline">Código de ética e conduta</a>
                      
                  </Container>

                  <Container className={'max-[550px]:items-center'}>
                      <p className="text-white font-bold">Fale conosco</p>
                      <p className="text-[#54595f] font-medium">contato@Wiinpay.com</p>
                      <p className="text-[#54595f] font-medium">+55 64 9 9223-1968</p>
                  </Container>

              </div>
          </section>

          <section className="flex mx-auto h-full w-full bg-black justify-center items-center">
              <div class="w-full max-w-[1100px] flex flex-col gap-3 justify-center items-center m-3 p-8">
                    <p className="text-[#54595f]">Wiinpay 2024 © Todos os direitos reservados</p>
                    <p className="text-[#54595f]">CNPJ: 38.322.428/0001-23</p>
              </div>
          </section>

          
        </div>
      </main>
    </>
  );
}
